[mypy]
# Include paths to vendored copies of secp256k1lab and ed25519lab, in order
# to avoid "import-not-found" errors in mypy's `--strict` mode
mypy_path = $MYPY_CONFIG_FILE_DIR/secp256k1lab/src:$MYPY_CONFIG_FILE_DIR/ed25519lab/src